name: CI
'on':
  push:
    branches:
      - master
      - next
  pull_request:
    branches:
      - master
      - next
jobs:
  test-node:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        node-version:
          - 18.16.1
          - 20.4.0
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run cover --if-present
        env:
          BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
          BITBUCKET_APP_PASSWORD: ${{ secrets.BITBUCKET_APP_PASSWORD }}
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-${{ matrix.test_number }}
          path-to-lcov: build/coverage/lcov.info
          parallel: true
  release:
    needs:
      - test-node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.7.0
        with:
          node-version: 18.16.1
          cache: npm
      - run: npm ci
      - run: npx semantic-release
        env:
          CI: 'true'
          PKGBUILD_PUBLISH: ${{ secrets.PKGBUILD_PUBLISH }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  finish:
    needs:
      - test-node
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build/coverage/lcov.info
          parallel-finished: true
